name: instagram_clone
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  cached_network_image: ^2.5.0
  camera: 0.5.8+17
  permission_handler: ^5.0.1+1
  app_settings: ^4.0.4
  provider: ^4.3.3
  path: ^1.7.0
  path_provider: ^1.6.27
  local_image_provider: ^2.2.1
  firebase_auth: ^0.20.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: VeganStyle
      fonts:
        - asset: assets/fonts/instafont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
